Lab1
egorzakharovv/TaskAutomation pull request #1
Opened 2022-02-20 11:46 UTC by egorzakharovv

2022-03-05 02:40 UTC, ydvorzhetskiy requested changes

2022-03-05 02:40 UTC, ydvorzhetskiy commented on lab1/.idea/compiler.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Предлагаю всю папку `.idea` добавить в .gitignore

2022-03-05 02:40 UTC, ydvorzhetskiy commented on lab1/pom.xml
> +    <artifactId>Дворжецкий</artifactId>
Хех) artifactId принято писать английскими и через дефис.
Пруф - https://maven.apache.org/guides/mini/guide-naming-conventions.html

2022-03-05 02:40 UTC, ydvorzhetskiy commented on lab1/src/main/java/Account.java
> +    String name;
А давайте модификатор ставить?)

2022-03-05 02:40 UTC, ydvorzhetskiy commented on lab1/src/main/java/Account.java
> +    public ArrayList<CreditOperation> creditOperations = new ArrayList<>();
Ну нет - по принципу двойной записи сама операция содержит и дебет и кредит.
Т.е. формально дебет и кредит не отделимы в рамках одной операции.

2022-03-05 02:40 UTC, ydvorzhetskiy commented on lab1/src/main/java/Account.java
> +    public int getMoney() {
По идее термин "деньги" не применим)
В действительности - деньги, это только остаток на счёте 50 или 51.

Предлагаю как раз использовать термин "остаток"

2022-03-05 02:40 UTC, ydvorzhetskiy commented on lab1/src/main/java/Account.java
> +        return  debit - credit;
Отлично, только ещё и начальные остатки есть)

2022-03-05 02:40 UTC, ydvorzhetskiy commented on lab1/src/main/java/DebitOperation.java
> +        }
Непонятен смысл этого return...

2022-03-05 02:40 UTC, ydvorzhetskiy commented on lab1/src/main/java/Main.java
> +        a1.debitOperations.add(new DebitOperation(150, 10, "10 Товаров купленных по 100р, продаем по 150"));
А вот здесь как раз и косяк - обратите внимание, что дебет и кредит не совпадают для данной операции.
Вот если в рамках одной операции задавал бы сумма, то не оставалось бы шансов не совпасть)

Кстати, продажу поэтому делают через дополнительный счёт 90.
С номерами и счетами можете бегло ознакомиться по ссылке - http://www.consultant.ru/document/cons_doc_LAW_29165/fd05066bbb0a451cf5dc95b2af35808cbef2509e/

2022-03-10 15:00 UTC, merged

2022-03-10 15:11 UTC, egorzakharovv commented
https://github.com/egorzakharovv/TaskAutomation/tree/Lab1_new